FROM oven/bun:1


WORKDIR /usr/src

COPY packages ./packages
RUN cd packages/db && bun install 
RUN cd packages/db && bunx prisma generate 


COPY package*.json ./
COPY ./bun.lock ./bun.lock
RUN bun install

COPY apps/web ./apps/web
RUN cd apps/web && bun install

EXPOSE 3000

CMD ["bun", "run", "web"]
