FROM oven/bun:1

WORKDIR /app

# copy root lock + config
COPY package.json bun.lock turbo.json ./

# copy only web app
COPY apps/web ./apps/web

WORKDIR /app/apps/web
RUN bun install

EXPOSE 3000
CMD ["bun", "run", "dev"]
